#!/usr/bin/env bash

function aptly_profile {
  local shome="${_aptly_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  export APTLY_VERSION="0.9.7"
}

aptly_profile
